// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwytvhhfdflebzrndbrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3eXR2aGhmZGZsZWJ6cm5kYnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDUwMzIsImV4cCI6MjA1NzI4MTAzMn0.RdQiuUuxxU_bbAiqhM5XOjS9ODgFvIQXs-wBKIo59O0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);